#travis configuration for coverage testing
dist: xenial
language: cpp

sudo: false # only for faster builds
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7  && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
