language: cpp
os: linux
dist: bionic
addons:
  apt:
    packages: libunwind-dev
notifications:
  email:
    if: branch = master OR branch = develop
script: ./src/foundation/tools/travis-unix.sh
jobs:
  include:
    - name: Linux GCC
      compiler: gcc
    - name: Windows MSVC
      os: windows
      script: ./src/foundation/tools/travis-windows-msvc.bat
    - name: macOS Clang
      os: osx
      compiler: clang
    - name: Linux Clang
      compiler: clang
    - name: Windows Clang
      os: windows
      install: choco install ninja
      script: ./src/foundation/tools/travis-windows-clang.bat
